name: Deploy to AWS Ubuntu

on:
  push:
    branches:
      - main  # Runs on push to the 'main' branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH and Deploy to AWS
        env:
          AWS_GITHUB: ${{ secrets.AWS_GITHUB }}
        run: |
          echo "Setting up SSH key..."
          echo "${{ secrets.AWS_GITHUB }}" > aws_key.pem
          chmod 600 aws_key.pem

          echo "Connecting to AWS Ubuntu Instance..."
          ssh -o StrictHostKeyChecking=no -i aws_key.pem ubuntu@54.167.30.97 << 'EOF'
            
            # Update system packages
            sudo apt update -y && sudo apt upgrade -y

            # Install Nginx & Git
            sudo apt install -y nginx git

            # Allow Nginx through firewall
            sudo ufw allow 'Nginx Full'

            # Remove old repo if exists
            sudo rm -rf /var/www/aws_cicd

            # Clone the latest repo
            sudo git clone https://github.com/Zed-Kryp/aws_cicd.git /var/www/aws_cicd

            # Change ownership to Nginx user
            sudo chown -R www-data:www-data /var/www/aws_cicd

            # Set up Nginx to serve index.html
            echo 'server {
                listen 80;
                server_name 54.87.108.158;

                root /var/www/aws_cicd;
                index index.html;

                location / {
                    try_files $uri $uri/ =404;
                }
            }' | sudo tee /etc/nginx/sites-available/aws_cicd

            # Enable the new site
            sudo ln -sf /etc/nginx/sites-available/aws_cicd /etc/nginx/sites-enabled/
            
            # Remove default Nginx page
            sudo rm -f /etc/nginx/sites-enabled/default

            # Restart Nginx
            sudo systemctl restart nginx
            sudo systemctl enable nginx

          EOF

      - name: Cleanup
        run: rm -f aws_key.pem
